-- Starter merchant dictionary.
--
-- Aliases are the cleaned tokens a descriptor reduces to, not the raw strings.
-- 'SQ *TST* STARBUCKS 800-782-7282 CA' becomes 'starbucks' after cleaning, and
-- that is what gets matched -- so one alias covers a whole family of processor
-- prefixes, store numbers and phone numbers.

INSERT INTO merchants (id, display_name, category) VALUES
    ('mch_starbucks',  'Starbucks',        'Food and Drink'),
    ('mch_heb',        'H-E-B',            'Groceries'),
    ('mch_wholefoods', 'Whole Foods',      'Groceries'),
    ('mch_traderjoes', 'Trader Joe''s',    'Groceries'),
    ('mch_amazon',     'Amazon',           'Shopping'),
    ('mch_apple',      'Apple',            'Shopping'),
    ('mch_target',     'Target',           'Shopping'),
    ('mch_walmart',    'Walmart',          'Shopping'),
    ('mch_uber',       'Uber',             'Transport'),
    ('mch_lyft',       'Lyft',             'Transport'),
    ('mch_shell',      'Shell',            'Transport'),
    ('mch_chevron',    'Chevron',          'Transport'),
    ('mch_netflix',    'Netflix',          'Entertainment'),
    ('mch_spotify',    'Spotify',          'Entertainment'),
    ('mch_steam',      'Steam',            'Entertainment'),
    ('mch_chipotle',   'Chipotle',         'Food and Drink'),
    ('mch_mcdonalds',  'McDonald''s',      'Food and Drink'),
    ('mch_dunkin',     'Dunkin''',         'Food and Drink'),
    ('mch_cvs',        'CVS',              'Health'),
    ('mch_walgreens',  'Walgreens',        'Health'),
    ('mch_delta',      'Delta Air Lines',  'Travel'),
    ('mch_united',     'United Airlines',  'Travel'),
    ('mch_marriott',   'Marriott',         'Travel'),
    ('mch_att',        'AT&T',             'Bills'),
    ('mch_verizon',    'Verizon',          'Bills'),
    ('mch_comcast',    'Comcast',          'Bills')
ON CONFLICT (id) DO NOTHING;

INSERT INTO merchant_aliases (merchant_id, pattern, source, weight) VALUES
    ('mch_starbucks',  'starbucks',        'seed', 1.0),
    ('mch_starbucks',  'starbucks mobile', 'seed', 1.0),
    ('mch_starbucks',  'sbux',             'seed', 0.9),
    ('mch_heb',        'heb',              'seed', 1.0),
    ('mch_heb',        'h e b',            'seed', 1.0),
    ('mch_heb',        'heb grocery',      'seed', 1.0),
    ('mch_wholefoods', 'whole foods',      'seed', 1.0),
    ('mch_wholefoods', 'wholefds',         'seed', 0.9),
    ('mch_wholefoods', 'wfm',              'seed', 0.7),
    ('mch_traderjoes', 'trader joes',      'seed', 1.0),
    ('mch_traderjoes', 'trader joe s',     'seed', 1.0),
    ('mch_amazon',     'amazon',           'seed', 1.0),
    ('mch_amazon',     'amzn mktp',        'seed', 1.0),
    ('mch_amazon',     'amazon prime',     'seed', 1.0),
    ('mch_apple',      'apple',            'seed', 1.0),
    ('mch_apple',      'apple com bill',   'seed', 1.0),
    ('mch_target',     'target',           'seed', 1.0),
    ('mch_walmart',    'walmart',          'seed', 1.0),
    ('mch_walmart',    'wal mart',         'seed', 1.0),
    ('mch_walmart',    'wm supercenter',   'seed', 0.9),
    ('mch_uber',       'uber',             'seed', 1.0),
    ('mch_uber',       'uber trip',        'seed', 1.0),
    ('mch_uber',       'uber eats',        'seed', 0.8),
    ('mch_lyft',       'lyft',             'seed', 1.0),
    ('mch_lyft',       'lyft ride',        'seed', 1.0),
    ('mch_shell',      'shell',            'seed', 1.0),
    ('mch_shell',      'shell oil',        'seed', 1.0),
    ('mch_chevron',    'chevron',          'seed', 1.0),
    ('mch_netflix',    'netflix',          'seed', 1.0),
    ('mch_spotify',    'spotify',          'seed', 1.0),
    ('mch_spotify',    'spotify usa',      'seed', 1.0),
    ('mch_steam',      'steam',            'seed', 0.9),
    ('mch_steam',      'steamgames com',   'seed', 1.0),
    ('mch_chipotle',   'chipotle',         'seed', 1.0),
    ('mch_mcdonalds',  'mcdonalds',        'seed', 1.0),
    ('mch_dunkin',     'dunkin',           'seed', 1.0),
    ('mch_cvs',        'cvs',              'seed', 1.0),
    ('mch_cvs',        'cvs pharmacy',     'seed', 1.0),
    ('mch_walgreens',  'walgreens',        'seed', 1.0),
    ('mch_delta',      'delta air',        'seed', 1.0),
    ('mch_united',     'united airlines',  'seed', 1.0),
    ('mch_marriott',   'marriott',         'seed', 1.0),
    ('mch_att',        'att',              'seed', 0.8),
    ('mch_att',        'at t',             'seed', 0.9),
    ('mch_verizon',    'verizon',          'seed', 1.0),
    ('mch_comcast',    'comcast',          'seed', 1.0)
ON CONFLICT DO NOTHING;
